# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 18:58
from __future__ import unicode_literals

import chores.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_on', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.IntegerField(validators=[chores.models.validate_points])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='chore',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.Task'),
        ),
    ]
